# Generated by Django 3.2.8 on 2023-03-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_x_persona', models.FloatField(default=0.2)),
                ('porcentaje_subtotal_reservacion', models.FloatField(default=0.03)),
            ],
        ),
    ]
