# Generated by Django 3.2.8 on 2023-03-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.FloatField()),
                ('amount_me', models.FloatField()),
                ('amount_property', models.FloatField()),
                ('date_register', models.DateField(auto_now_add=True)),
                ('date_payment', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
