# Generated by Django 3.2.8 on 2023-03-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_code'),
        ('setting', '0004_history_transaccion_propertys'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_transaccion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
