# Generated by Django 3.2.8 on 2023-03-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='documentI',
            field=models.FileField(upload_to='CC'),
        ),
    ]
