# Generated by Django 3.2.8 on 2023-03-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_multimedia_documenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
