# Generated by Django 3.2.8 on 2023-03-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enter', models.CharField(max_length=12)),
                ('date_exit', models.CharField(max_length=12)),
                ('user_email', models.EmailField(max_length=254)),
                ('boys', models.IntegerField()),
                ('adult', models.IntegerField()),
                ('price', models.IntegerField()),
                ('hour_input', models.CharField(max_length=20)),
                ('note', models.TextField()),
                ('days', models.IntegerField(default=1)),
                ('status', models.CharField(default='En espera', max_length=45)),
                ('limpieza', models.IntegerField(blank=True, default=0, null=True)),
                ('money_returned', models.IntegerField(default=0)),
                ('propertys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
