# Generated by Django 3.2.8 on 2023-03-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_propietrio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='name_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
